### ISSUE TITLE
BUG object tools link is partly hidden.

### ISSUE THREAD

**Issue by svandeneertwegh** [fsbraun/djangocms-simple-admin-style#3]
<img width="316" alt="Schermafbeelding 2023-08-26 om 12 39 18" src="https://github.com/fsbraun/djangocms-simple-admin-style/assets/34129243/f470573e-283a-4c15-a014-0fe1cdee3864">

I added this to the admin-style.. css:
`#changelist {
    margin-top: 20px!important;
}
.object-tools {
    padding-top: 20px !important;
}`

Now with the above code added, it looks like this:
<img width="261" alt="Schermafbeelding 2023-08-26 om 12 40 31" src="https://github.com/fsbraun/djangocms-simple-admin-style/assets/34129243/85b1c90a-0e3d-4147-aa04-03e962ae8828">

**Comment by fsbraun** [comment]
Fixed in 0.4.9
